---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endlesssurvival
  annotations:
      keel.sh/policy: force
      keel.sh/match-tag: 'true'
      keel.sh/pollSchedule: '@every 1m'
      keel.sh/trigger: poll
spec:
  selector:
    matchLabels:
      app: endlesssurvival
  replicas: 1
  template:
    metadata:
      labels:
        app: endlesssurvival
    spec:
      containers:
        - name: endlesssurvival
          image: jwhitbread/endlesssurvival:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            
          livenessProbe:
            exec:
              command:
              - curl
              - --fail
              - https://endlesssurvival.uk/health_check
            initialDelaySeconds: 10
            timeoutSeconds: 30
            failureThreshold: 1
            successThreshold: 1